language: objective-c
osx_image: xcode7
xcode_project: Example/HNKGooglePlacesAutocomplete-Example.xcworkspace
xcode_scheme: HNKGooglePlacesAutocomplete-Example
podfile: Example/Podfile

script:
   - xcodebuild test -workspace Example/HNKGooglePlacesAutocomplete-Example.xcworkspace -scheme HNKGooglePlacesAutocomplete-Example -sdk iphonesimulator
